### PR TITLE
Header and footer

### PR DESCRIPTION
**Pull request by zhorabay**
- [ ] In this branch, I:
- Created page header according to the wireframe;
- Added logo;
- Created page footer according to the wireframe;

### CODE REVIEW

**Comment by zhorabay** [comment]
I set darkblue background to both header & footer for now. We will change it later when we give a style to the whole project

**Comment by zhorabay** [comment]
I added a logo, but webpack doesn't read the images. I tried to use different image formats. Can you fix it? I don't know what is the problem :(

**Comment by bhushan354** [comment]
- Hii @zhorabay I have fixed the issue .
- The issue was there because we have not added a webpack plugin and loader for files like images and png.

**Review by bhushan354 — APPROVED** [review]
Status: Approved ✔️
Hi @zhorabay and @bhushan354 👋🏽,

Your headers and footers are completed !!, There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

image


Highlights
- linters are passing :white_check_mark: 
- Documented your work properly  :white_check_mark: 
- webpack and other plugins setup properly  :white_check_mark: 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
